services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    env_file:
      - .env
    environment:
      APP_URL: ${APP_URL:-http://localhost:8080}
    volumes:
      - .:/var/www/html
      - web-build:/var/www/html/public/build
    ports:
      - "8080:80"
      - "5173:5173"
    depends_on:
      pgsql:
        condition: service_healthy

  pgsql:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-mydb}
    volumes:
      - db:/var/lib/postgresql/data
      - ./.docker/evo-db:/docker-entrypoint-initdb.d
    ports:
      - "${FORWARD_DB_PORT:-5438}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME:-root} -d ${DB_DATABASE:-mydb}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  evolution-go:
    image: evoapicloud/evolution-go:latest
    ports:
      - "${EVOLUTION_PORT:-8081}:${EVOLUTION_PORT:-8081}"
    environment:
      SERVER_PORT: ${EVOLUTION_PORT:-8081}
      CLIENT_NAME: evolution
      GLOBAL_API_KEY: ${EVOLUTION_API_KEY:-sua-chave-segura-aqui}
      POSTGRES_AUTH_DB: postgresql://${DB_USERNAME:-root}:${DB_PASSWORD:-password}@pgsql:5432/evogo_auth?sslmode=disable
      POSTGRES_USERS_DB: postgresql://${DB_USERNAME:-root}:${DB_PASSWORD:-password}@pgsql:5432/evogo_users?sslmode=disable
      DATABASE_SAVE_MESSAGES: "false"
      WADEBUG: INFO
      LOGTYPE: console
    depends_on:
      pgsql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db:
    driver: local
  web-build:
    driver: local
