[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
environment=APP_URL="%(ENV_APP_URL)s"

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
